version:  '3.9'
services: 
    sistema_concrete_java:
      container_name: sistema_concrete_java
      image: lucasvscosta/validador-cpf-turma-devops
      ports: 
        - "3001:8080"
    sistema_concrete_csharp:
      container_name: sistema_concrete_csharp
      image: lucasvscosta/validador-cpf-csharp-turma-devops
      ports: 
        - "3002:80"        
